include:
  - docker/keycloak/compose.yml
services:
  red55.uma.authz.proxy:
    hostname: authz.house
    image: ${DOCKER_REGISTRY-}red55umaauthzproxy
    cap_add:
      - NET_ADMIN
      - NET_RAW
    build:
      context: .
      dockerfile: src/Red55.Uma.Authz.Proxy/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.red55-oidc-authz-proxy.rule=Host(`authz.house`)"
      - "traefik.http.routers.red55-uma-authz-proxy.entrypoints=http"
      - "traefik.http.services.red55-uma-authz-proxy.loadbalancer.server.port=8080"
   
  traefik:
    container_name: traefik
    image: docker.io/traefik:v3
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command:
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --entrypoints.https.http.tls=true
      #- --entrypoints.http.http.redirections.entrypoint.to=https
      #- --entrypoints.http.http.redirections.entrypoint.scheme=https
      # - --entrypoints.http.http.redirections.entrypoint.permanent=true
      - --log=true
      #- --log.filePath=/logs/traefik.log
      - --log.level=INFO # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/logs/access.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=204-299,400-499,500-599
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --api=true
      - --api.insecure=true
      - --api.dashboard=true
      - --ping=true
     
      #- --entrypoints.https.http.tls.certresolver=le_prod
      #- --certificatesresolvers.le_prod.acme.email=lkorokh@gmail.com
      #- --certificatesresolvers.le_prod.acme.storage=/acme/acme.json
      #- --certificatesresolvers.le_prod.acme.httpchallenge=true
      #- --certificatesresolvers.le_prod.acme.httpchallenge.entrypoint=http
      #- --certificatesresolvers.le_prod.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --serversTransport.insecureSkipVerify=true
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 5s
      retries: 60
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard
    depends_on:
      kc:
        condition: service_healthy
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
