---
Logging:
  LogLevel:
    Default: Debug
    Microsoft.AspNetCore: Warning

Serilog:
  MinimumLevel: 
    Default: "Debug"

Kestrel:
  Endpoints:
    http:
      Url: "http://+:8080"
ReverseProxy:
  Clusters:
    kc:
      HttpClient:
        DangerousAcceptAnyServerCertificate: true
      Destinations:
        kc:
          Address: https://kc:8443
  Routes:
    test-realm:
      ClusterId: kc
      Match:
        Path: "/realms/test/protocol/openid-connect/token"
      Transforms:
        - RequestHeadersCopy: 'true'
        - RequestHeaderRemove: "Host"
        - RequestHeader: "Host"
          Set: "authz.house"
        - ResponseHeadersCopy: 'true'
        - UmaAuthzTokenEndpoint: "/realms/test/protocol/openid-connect/token"
          azp: "gitlab"        
AppConfig:
  UmaServerBaseUrl: "https://kc:8443"
  InsecureSkipTlsVerify: true

