---
Logging:
  LogLevel:
    Default: Debug
    Microsoft.AspNetCore: Warning

Serilog:
  MinimumLevel: 
    Default: "Debug"

Kestrel:
  Endpoints:
    http:
      Url: "http://+:8080"
ReverseProxy:
  Clusters:
    kc:
      HttpClient:
        DangerousAcceptAnyServerCertificate: true
      Destinations:
        kc:
          Address: http://kc:8080
  Routes:
    test-realm:
      ClusterId: kc
      Match:
        Path: "/realms/test/protocol/openid-connect/token"
      Transforms:
        - RequestHeaderRemove: "Host"
        - RequestHeader: "Host"
          Set: "authz.house"
        - RequestHeadersCopy: 'true'       
        - ResponseHeadersCopy: 'true'
        - UmaAuthzResponse: "/realms/test/protocol/openid-connect/token"
          azp: "gitlab"
AppConfig:
  UmaServerBaseUrl: "http://kc.house:8080"
