name: CI - On Main Branch Tag
on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ["CI - On Main Branch Push"]
    types:
      - completed
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  build-push:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 50
          fetch-tags: true
      - name: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: red55/uma-authz-proxy
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=sha
      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: src/Red55.Uma.Authz.Proxy/Dockerfile
          push: true
          tags: "${{ env.DOCKER_METADATA_OUTPUT_TAGS }}"
          labels: "${{ env.DOCKER_METADATA_OUTPUT_LABELS }}"
